# Site settings
title: Yu Wang
description: 'Yu Wang - a software engineer and designer'
url: 'http://joshgerdes.com/jekyll-uno'
baseurl: '/yu/'
# google_analytics: 'UA-XXXXXX-X'
disqus_shortname: 'yu'

author:
  name: 'Yu Wang'
  email: wangyu2165@gmail.com
  facebook_username: wangyu2165
  github_username: yuwang17
  linkedin_username: wangyu2165

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
